export const mockData = [
  {
    id: "2",
    name: "Jimmy Donaldson",
    username: "mrbeast",
    profileImage: "/mrbeast.jpeg",
    bio: "Philanthropist and YouTuber known for insane challenges, giveaways, and raising millions for charity.",
    followers: 200000000,
    platforms: [
      {
        name: "YouTube",
        handle: "mrbeast",
        url: "https://www.youtube.com/user/mrbeast6000",
      },
      {
        name: "Twitter",
        handle: "mrbeast",
        url: "https://twitter.com/mrbeast",
      },
      {
        name: "Instagram",
        handle: "mrbeast",
        url: "https://instagram.com/mrbeast",
      },
    ],
    genres: ["Philanthropy", "Entertainment", "Challenges"],
    collaborations: ["Beast Burger", "Team Trees", "Team Seas"],
    ratings: 4.9,
  },
  {
    id: "2",
    name: "James Rodriguez",
    username: "jamesthelens",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
    bio: "Fitness coach inspiring people to achieve their health goals.",
    followers: 85000,
    platforms: [
      {
        name: "YouTube",
        handle: "James Rodriguez",
        url: "https://youtube.com/c/jamesrodriguez",
      },
      {
        name: "Instagram",
        handle: "@jamesthelens",
        url: "https://instagram.com/jamesthelens",
      },
    ],
    genres: ["Fitness", "Health"],
    collaborations: ["Nike", "MyProtein", "Under Armour"],
    ratings: 4.7,
  },
  {
    id: "3",
    name: "Emily Zhang",
    username: "emilyzkitchen",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
    bio: "Sharing quick, healthy recipes for busy foodies.",
    followers: 65000,
    platforms: [
      {
        name: "Instagram",
        handle: "@emilyzkitchen",
        url: "https://instagram.com/emilyzkitchen",
      },
      {
        name: "TikTok",
        handle: "@emilyzkitchen",
        url: "https://tiktok.com/emilyzkitchen",
      },
    ],
    genres: ["Food", "Cooking"],
    collaborations: ["Whole Foods", "Blue Apron", "Tupperware"],
    ratings: 4.9,
  },
  {
    id: "4",
    name: "Alex Nguyen",
    username: "alexnguyenshots",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    bio: "Travel photographer capturing moments from around the world.",
    followers: 180000,
    platforms: [
      {
        name: "Instagram",
        handle: "@alexnguyenshots",
        url: "https://instagram.com/alexnguyenshots",
      },
      {
        name: "YouTube",
        handle: "Alex Nguyen",
        url: "https://youtube.com/c/alexnguyen",
      },
    ],
    genres: ["Photography", "Travel"],
    collaborations: ["Canon", "National Geographic", "Airbnb"],
    ratings: 4.6,
  },
  {
    id: "5",
    name: "Rachel Kim",
    username: "rachelreacts",
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
    bio: "Tech enthusiast reviewing the latest gadgets and apps.",
    followers: 95000,
    platforms: [
      {
        name: "YouTube",
        handle: "Rachel Kim",
        url: "https://youtube.com/c/rachelkim",
      },
      {
        name: "Twitter",
        handle: "@rachelreacts",
        url: "https://twitter.com/rachelreacts",
      },
    ],
    genres: ["Tech", "Reviews"],
    collaborations: ["Samsung", "Google", "Best Buy"],
    ratings: 4.7,
  },
];
